kind: pipeline
type: docker
name: Nautobot discovery and Population Pipeline


steps:
- name: debug-python-environment
  image: deadtree101/netauto
  network_mode: host
  commands:
    - python --version
    - python -m pip list

- name: Validate and Initialize Git
  image: deadtree101/netauto:latest
  network_mode: host
  volumes:
    - name: backup_volume
      path: /home/devtree/Code/Nautobot_device_backups
  commands:
    - |
      echo "Checking if /mnt/backup is a Git repository..."
      if [ ! -d "/mnt/backup/.git" ]; then
        echo "/mnt/backup is not a Git repository. Initializing..."
        cd /mnt/backup
        git init
        git remote add origin git@github.com:routemypacket/Nautobot_device_backups.git
        echo "Git repository initialized successfully."
      else
        echo "/mnt/backup is a valid Git repository."
      fi
      cd /mnt/backup
      git pull origin main || echo "Warning: Pull failed. Check branch name or connectivity."
  
- name: Populate Nautobot from sandbox iosXR device
  image: deadtree101/netauto
  network_mode: host
#  environment:
#    MY_PASS:
#      from_secret: MY_PASS
  volumes:
    - name: backup_volume
      path: /home/devtree/Code/Nautobot_device_backups
  commands:
# - pip3 install -r requirements.txt
  - python3 /drone/src/populate_nautobot_device.py

volumes:
  - name: backup_volume
    host:
      path: /home/devtree/Code/Nautobot_device_backups

trigger:
  branch:
    exclude:
    - master

#te