kind: pipeline
type: docker
name: Nautobot discovery and Population Pipeline


steps:
#- name: debug-python-environment
#  image: deadtree101/netauto
#  network_mode: host
#  commands:
#    - python --version
#    - python -m pip list


- name: Populate Nautobot from sandbox iosXR device
  image: deadtree101/netauto
  network_mode: host
#  environment:
#    MY_PASS:
#      from_secret: MY_PASS
  commands:
# - pip3 install -r requirements.txt
  - python3 /drone/src/populate_nautobot_device.py


trigger:
  branch:
    exclude:
    - master

#tes